asrama:
    path:     /
    defaults: { _controller: "MonitorMonitorBundle:Asrama:index" }

asrama_show:
    path:     /{id}/show
    defaults: { _controller: "MonitorMonitorBundle:Asrama:show" }

asrama_new:
    path:     /new
    defaults: { _controller: "MonitorMonitorBundle:Asrama:new" }

asrama_create:
    path:     /create
    defaults: { _controller: "MonitorMonitorBundle:Asrama:create" }
    methods:  POST

asrama_edit:
    path:     /{id}/edit
    defaults: { _controller: "MonitorMonitorBundle:Asrama:edit" }

asrama_update:
    path:     /{id}/update
    defaults: { _controller: "MonitorMonitorBundle:Asrama:update" }
    methods:  [POST, PUT]

asrama_delete:
    path:     /{id}/delete
    defaults: { _controller: "MonitorMonitorBundle:Asrama:delete" }
    methods:  [POST, DELETE]
