Monitor\MonitorBundle\Entity\Penghuni:
 type: entity
 repositoryClass: Monitor\MonitorBundle\Repository\PenghuniRepository
 table: penghuni
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  tanggal:
   type: date
  is_active:
   type: boolean
  created_at:
   type: datetime
  updated_at:
   type: datetime
   nullable: true
  token:
   type: string
   length: 255
   unique: true
 manyToOne:
  ruangan:
   targetEntity: Ruangan
   inversedBy: penghuni
   joinColumn:
    name: ruangan_id
    referencedColumnName: id
  orang:
   targetEntity: Orang
   inversedBy: penghuni
   joinColumn:
    name: orang_id
    referencedColumnName: id
 lifecycleCallbacks:
  prePersist: [setCreatedAtValue, setTokenValue, setIsActiveValue ]
  preUpdate: [ setUpdatedAtValue ]
