Monitor\MonitorBundle\Entity\User:
 type: entity
 repositoryClass: Monitor\MonitorBundle\Repository\UserRepository
 table: user
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  created_at:
   type: datetime
  is_delete:
   type: boolean
   nullable: true
  updated_at:
   type: datetime
   nullable: true
  token:
   type: string
   length: 255
   unique: true
 manyToOne:
  asrama:
   targetEntity: Asrama
   inversedBy: user
   joinColumn:
    name: asrama_id
    referencedColumnName: id
 lifecycleCallbacks:
  prePersist: [setCreatedAtValue, setTokenValue ]
  preUpdate: [ setUpdatedAtValue ]
