<?php

namespace Monitor\MonitorBundle\Repository;

/**
 * AsramaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsramaRepository extends \Doctrine\ORM\EntityRepository
{
}
