<?php

namespace Monitor\MonitorBundle\Repository;

/**
 * KabupatenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KabupatenRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByProvince($province)
	{
		return $this
		->createQueryBuilder('kabupaten')
		->join('kabupaten.provinsi', 'provinsi')
		->andWhere('provinsi.id = :province')
		->setParameter('province', $province)
		->getQuery()
		->getResult();
	}
}
