<?php

namespace Monitor\MonitorBundle\Repository;

/**
 * OrangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrangRepository extends \Doctrine\ORM\EntityRepository
{
	public function getOrang()
	{
		$query = $this->getEntityManager()
			->createQuery('
				select o from MonitorMonitorBundle:Orang o
				where o.is_delete = :is
				order by o.created_at, o.nama
			')->setParameters(array(
				'is' => false
			));
		
		return $query->getResult();
	}
	
	public function getOrangQuery()
	{
		$query = $this->getEntityManager()
			->createQuery('
				select o from MonitorMonitorBundle:Orang o
				where o.is_delete = :is
				order by o.no_identitas asc
			')->setParameters(array(
				'is' => false
			));
		
		return $query;
	}
	
	public function getSelectedOrang($key = null)
	{
		$query = $this->getEntityManager()
			->createQuery('
				select o from MonitorMonitorBundle:Orang o
				where (o.nama like :key or o.no_identitas like :key)
				and o.is_delete = :is
				order by o.created_at, o.nama
			')
			->setParameters(
				array(
					'is' => false,
					'key' => '%'.$key.'%',
				)
			);
			
		return $query->getResult();
	}
}
