<?php

namespace Monitor\MonitorBundle\Repository;

/**
 * OrangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrangRepository extends \Doctrine\ORM\EntityRepository
{
}
