<?php

namespace Monitor\MonitorBundle\Repository;

/**
 * PenghuniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PenghuniRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPenghuni($idru)
	{
		$query = $this->getEntityManager()
			->createQuery('
				select p from MonitorMonitorBundle:Penghuni p 
				inner join p.orang o
				inner join p.ruangan r
				where r.id = :idru
				order by p.created_at asc
			')->setParameters(array('idru' => $idru));
		
		return $query->getResult();
	}
	
	public function getPenghuniQuery($idru)
	{
		$query = $this->getEntityManager()
			->createQuery('
				select p from MonitorMonitorBundle:Penghuni p
				inner join p.orang o
				inner join p.ruangan r
				where r.id = :idru
				order by p.created_at asc
			')->setParameters(array('idru' => $idru));
		
		return $query;
	}
}
