<?php

namespace Monitor\MonitorBundle\Repository;

/**
 * PenghuniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PenghuniRepository extends \Doctrine\ORM\EntityRepository
{
}
