<?php

namespace Monitor\MonitorBundle\Repository;

/**
 * RuanganRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuanganRepository extends \Doctrine\ORM\EntityRepository
{
}
