<?php

namespace Monitor\MonitorBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUserQuery()
	{
		$query = $this->getEntityManager()
			->createQuery('
				select u from MonitorMonitorBundle:User u
				where u.is_delete = :is
			')
			->setParameters(array(
				'is' => false
			));
		
		return $query;
	}
}
